from sys import argv
import sys
from xlrd import open_workbook

# eror checking of the usage
if len(argv) != 3:
	print "================================================================="
	print "== Error: Wrong usage of command line arguments                =="
	print "== Usage: python <script.py> [xls_filename] [csv_filename]     =="
	print "==        follow the exact order of the arguments              =="
	print "================================================================="
	sys.exit(-1);

# open the workbook
wb = open_workbook(argv[1])

# csvfilename does not matter, generated by the system
# needs to be removed later
csv_filename = argv[2]
# open the output data file
data_output = open(csv_filename, 'w')
# truncate the file
data_output.truncate()

# navigate the work sheet
period = ','
for s in wb.sheets():
	for row in range(s.nrows):
		new_line = ""
		for col in range(s.ncols):
			new_line += str(s.cell(row, col).value)
			new_line += period
		# debuging
		# print new_line
		data_output.write(new_line)
		data_output.write("\n")
# close the file
data_output.close()