from sys import argv
import sys
from xlrd import open_workbook

# eror checking of the usage
if len(argv) != 4:
	print "================================================================================="
	print "== Error: Wrong usage of command line arguments                                =="
	print "== Usage: python <script.py> [xls_filename] [visual_output.html] [plot_type]   =="
	print "== Plot_type: scatter, bar, line,                                              =="
	print "==        follow the exact order of the arguments                              =="
	print "================================================================================="
	sys.exit(-1);

# open the workbook
wb = open_workbook(argv[1])

plot_type = argv[3]
# csvfilename does not matter, generated by the system
# needs to be removed later
csv_filename = "data.csv"
# open the output data file
data_output = open(csv_filename, 'w')
# truncate the file
data_output.truncate()

# navigate the work sheet
period = ','
for s in wb.sheets():
	for row in range(s.nrows):
		new_line = ""
		for col in range(s.ncols):
			new_line += str(s.cell(row, col).value)
			new_line += period
		# debuging
		# print new_line
		data_output.write(new_line)
		data_output.write("\n")
# close the file
data_output.close()

# open visual output file 
visual_filename = argv[2]
visual_output = open(visual_filename, 'w')
visual_output.truncate()

if plot_type == "scatter":
	x_index_found = 0
	y_index_found = 0
	magnifer_found = 0
	radius_found = 0
	datafile_found = 0
	# can change the user input to command line input if needed
	x_index_name = raw_input("Please enter x_index_name: ")
	y_index_name = raw_input("Please enter y_index_name: ")

	with open("scatter_template.html") as file:
		for line in file:
			# determine whether we need to modify the template arguments
			if "x_index" in line and x_index_found == 0:
				x_index_found += 1
				line = "var x_index = \"" + str(x_index_name) + "\";\n";
			elif "y_index" in line and y_index_found == 0:
				y_index_found += 1
				line = "var y_index = \"" + str(y_index_name)+ "\";\n";
			elif "magnifer" in line and magnifer_found == 0:
				magnifer_found += 1
				# line = "var magnifer = \"" + str(magnifer)+ "\";\n";
				# print line
			elif "radius" in line and radius_found == 0:
				radius_found += 1
				# line = "var radius = \"" + str(x_index_name)+ "\";\n";
				# print line
			elif "datafile" in line and datafile_found == 0:
				datafile_found += 1
				line = "var datafile = \"" + str(csv_filename)+ "\";\n";
			visual_output.write(line)
# elif plot_type == "bar":
# 	# with open("bar_template.html") as file:
# 	# 	for line in file:

# elif plot_type == "line":
# 	# with open("line_template.html") as file:
# 	# 	for line in file:
else:
	print "================================================================================="
	print "== Error: Wrong plot type                                					  =="
	print "== Plot_type: scatter, bar, line,                                              =="
	print "================================================================================="

visual_output.close()

